# -- Site Configuration --
theme: blowfish
baseURL: https://richeyward.github.io
defaultContentLanguage: en

enableRobotsTXT: true
paginate: 10
summaryLength: 0

buildDrafts: true
buildFuture: true

imaging:
  anchor: 'Center'

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
  series: "series"

sitemap:
  changefreq: 'daily'
  filename: 'sitemap.xml'
  priority: 0.5

outputs:
  home: ["HTML", "RSS", "JSON"]

related:
  threshold: 0
  toLower: false
  indices:
    - name: "tags"
      weight: 100
    - name: "categories"
      weight: 100
    - name: "series"
      weight: 50
    - name: "authors"
      weight: 20
    - name: "date"
      weight: 10
    - name: "fragmentrefs"
      type: "fragments"
      applyFilter: false
      weight: 10