baseURL: "https://richeyward.github.io"
theme: "LoveIt"
title: "Richey Ward"

languageCode: "en"
languageName: "English"

# # Markup related configuration in Hugo
# [markup]
#   # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
#   [markup.highlight]
#     # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
#     noClasses = false
