# Markup related config in Hugo
highlight:
  codeFences: true
  guessSyntax: true
  lineNos: true
  # lineNumbersInTable: true
  # false is a necessary configuration
  # (https://github.com/dillonzq/LoveIt/issues/158)
  noClasses: false

# Goldmark is from Hugo 0.60 the default library used for Markdown
goldmark:
  extensions:
    definitionList: true
    footnote: true
    linkify: true
    strikethrough: true
    table: true
    taskList: true
    typographer: true

tableOfContents:
  startLevel: 2
  endLevel: 6